# fly.toml app configuration file generated for https-zambezinvest-598891774533-us-west1-run-app-ref-zmb424432 on 2025-10-19T06:24:50Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'https-zambezinvest-598891774533-us-west1-run-app-ref-zmb424432'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
